spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    generate-unique-name: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
bot:
  token: ${BOT_TOKEN} # put your token here

thredpoolsize: ${THREADPOOLSIZE}

jwtSecret: VeryLongSecretKeyVeryLongSecretKeyVeryLongSecretKeyVeryLongSecretKeyVeryLongSecretKeyVeryLongSecretKey
jwtExpirationMs: 86400 # 24hours